### ISSUE TITLE
Cannot use yii\base\Object as Object because 'Object' is a special class name

### ISSUE THREAD

**Issue by far-east91** [codemix/yii2-excelexport#18]
![image](https://user-images.githubusercontent.com/10677551/35483910-c4ff8572-0482-11e8-967b-3564a04b9707.png)

**Comment by mikehaertl** [comment]
This is because we didn't change the code yet to be compatible with PHP 7.2. See the release notes of Yii 2.0.13 here: 
https://github.com/yiisoft/yii2/blob/2.0.13/framework/UPGRADE.md#upgrade-from-yii-2012

As I see it, this is a one way decision: Once we change this, the library will no longer work with Yii < 2.0.13. I'm not really sure yet, how we will solve this.

**Comment by mikehaertl** [comment]
@far-east91 I've pushed a fix to master. Could you maybe do a quick test if this fixes the issue? As soon as you confirm I will draft a new release.

**Comment by far-east91** [comment]
@mikehaertl i've pull the latest release and it solved the issue, thank you very much brother

**Comment by mikehaertl** [comment]
Published release 2.6.0 which requires at least Yii 2.0.13. For older Yii releases version 2.5.x should be used.
